direction: right

...@../../styles

example: safeDivide 10 then 0 then 1 {
  j10 -> div2
  div2 -> j5
  j5 -> div0
  div0 -> nothing
  nothing -> div1
  div1 -> nothing2
  j10: Just 10
  div2: bind safeDivide 2
  j5: Just 5
  div0: bind safeDivide 0
  nothing: Nothing
  div1: bind safeDivide 1
  nothing2: Nothing
  j10.class: [
    value
    a
  ]
  j5.class: [
    value
    a
  ]
  nothing.class: [
    type
    b
  ]
  nothing2.class: [
    type
    b
  ]
  div2.class: [
    function
    f
  ]
  div0.class: [
    function
    f
  ]
  div1.class: [
    function
    g
  ]
  div1: {tooltip: f is not called — Nothing is already present.}
}
