direction: right

classes: {
  type: {
    shape: circle
    width: 80
    style: {
      stroke-width: 1
      bold: true
      double-border: true
      opacity: 0.8
      font-size: 14
    }
  }
  value: {
    shape: circle
    width: 80
    style: {
      stroke-width: 1
      opacity: 0.7
      font-size: 14
    }
  }
  function: {
    shape: rectangle
    style: {
      border-radius: 5
      stroke-width: 1
      opacity: 0.9
      shadow: true
      font-size: 16
    }
  }
  comment: {
    width: 480
    shape: text
    style: {
      stroke-width: 0
      font-size: 14
    }
  }
  definition: {
    width: 600
    style: {
      border-radius: 5
      stroke-width: 1
      font-size: 20
    }
  }
  a: {
    style: {
      fill: "#f4a261"
    }
  }
  b: {
    style: {
      fill: "#9191f4"
    }
  }
  c: {
    style: {
      fill: "#f4f461"
    }
  }
  p: {
    style: {
      fill: "#99ff99"
    }
  }
  f: {
    style: {
      fill: "#f4a261"
    }
  }
  f2: {
    style: {
      fill: "#99ff99"
    }
  }
  g: {
    style: {
      fill: "#9191f4"
    }
  }
  h: {
    style: {
      fill: "#f4f461"
    }
  }
  code: {
    shape: rectangle
    style: {
      border-radius: 2
      stroke-width: 1
    }
  }
}
