direction: right

...@../styles

requirement: "Traversable requirements" {
  f_appl: "F must be Applicative" {
    style.fill: "#f4f4f4"
  }
  t_funct: "T must be Functor (+ Foldable)" {
    style.fill: "#f4f4f4"
  }
}
